# This shell script is to be run by developers on Linux.
# It will generate a general-purpose Makefile containing a target
#    for every CPP file within two subdirectories of this folder.

echo "# Awesome Makefile generated by ./genmake.sh" > Makefile
echo "# File consists of a lot of gobbledy followed by a target" >> Makefile;
echo "" >> Makefile;

echo "CFLAGS = \`pkg-config --cflags purple\`" >> Makefile;
# echo "FLAGS = '-Wall -fPIC'" >> Makefile;
echo "LIBS = \`pkg-config --libs purple\`" >> Makefile;
echo "LINKS = './google_v8/v8-read-only/libv8.a'" >> Makefile
echo "" >> Makefile;

FLAGS='-Wall -fPIC'

for subdir in ./*/ ./*/*/ ./; #Iterate 
  do
    for file in $subdir*.cc ;
      do
      {
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        printf ".objs/${pathless%.cc}.o: $file" >> Makefile;
        for i in `c_incl $file | gawk '/\/usr\/include/ { next } { print } '`;
        do
          printf " $i" >> Makefile;
        done;
        echo "" >> Makefile;
        
        echo "	-mkdir .objs" >> Makefile;
        echo "	\$(CXX) $FLAGS \$(CFLAGS) ${SYMBOL_FLAGS} ${OPTIMIZATION_FLAGS} -c  $file		-o .objs/${pathless%.cc}.o" >> Makefile;
      };
      done;
    for file in $subdir*.c ;
      do
      {
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        printf ".objs/${pathless%.c}.o: $file" >> Makefile;
        for i in `c_incl $file | gawk '/\/usr\/include/ { next } { print } '`;
        do
          printf " $i" >> Makefile;
        done;
        echo "" >> Makefile;
        
        echo "	-mkdir .objs" >> Makefile;
        echo "	\$(CC) $FLAGS \$(CFLAGS) ${SYMBOL_FLAGS} ${OPTIMIZATION_FLAGS} -c  $file		-o .objs/${pathless%.c}.o"  >> Makefile;
      };
      done;
  done;

echo "" >> Makefile;
echo "# Nobody knows the trouble I've seen, no... no... nooo..." >> Makefile;
printf "link:" >> Makefile;
  for subdir in */ */*/ ./; #Iterate 
    do
      for file in $subdir*.cc;
      do 
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        if [[ $pathless == standalone_* ]]; 
          then continue; 
          fi
        printf " .objs/${pathless%.cc}.o" >> Makefile; 
      done;
      for file in $subdir*.c;
      do 
        pathless="${file##*/}";
        if [[ $pathless == \** ]]; 
          then continue; 
          fi
        if [[ $pathless == standalone_* ]]; 
          then continue; 
          fi
        printf " .objs/${pathless%.c}.o" >> Makefile; 
      done;
    done;
    echo "" >> Makefile;
  
  echo "	\$(CXX) -shared -fPIC .objs/*.o \$(LIBS) \$(LINKS) -o pidgin_plus.so" >> Makefile;

echo "" >> Makefile;
echo "Release: link" >> Makefile;
echo "	 # Nothing to do here." >> Makefile;
echo "cleanRelease:" >> Makefile;
echo "	 rm ./.objs/*.o" >> Makefile;

echo "" >> Makefile;
